version: '3.8'

services:
  php:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./docker.conf:/usr/local/etc/php-fpm.d/docker.conf
      - .:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - php

  db:
    image: postgres:16
    ports:
      - "5432:5432" 
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: lara
