version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: lara
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
